### PR TITLE
fix(builder): Calculate the completion rate

### LINKED ISSUE #244: [Results page > Analytics tab > Completion rate]: showing 'Infinity' instead of a number
It seems to happen when there's a number of views, but the number of starts is zero.

image

### PR DESCRIPTION
**Pull request by Jorgelig**
Calculate the completion rate if both totalCompleted and totalStarts are defined and are not zero

image

Closes #244

### CODE REVIEW

File: apps/builder/src/features/analytics/components/StatsCards.tsx [hunk 1]
```diff
@@ -10,6 +10,16 @@ import {
 import { Stats } from 'models'
 import React from 'react'
 
+const calculateCompletionRate = (
+  totalCompleted: number,
+  totalStarts: number
+): string => {
+  if (!totalCompleted || !totalStarts) return 'Not available'
+  if (isNaN(totalCompleted) || isNaN(totalStarts)) return 'Not available'
```
Comment (baptisteArno) [inline apps/builder/src/features/analytics/components/StatsCards.tsx:18]: These 2 lines can be removed because we know that `totalCompleted` and `totalStarts` are defined numbers

```suggestion

```

File: apps/builder/src/features/analytics/components/StatsCards.tsx [hunk 2]
```diff
@@ -10,6 +10,16 @@ import {
 import { Stats } from 'models'
 import React from 'react'
 
+const calculateCompletionRate = (
```
Comment (baptisteArno) [inline apps/builder/src/features/analytics/components/StatsCards.tsx:13]:
```suggestion
const computeCompletionRate = (
```

I prefer this naming if it's ok with you! 👌

**Review by baptisteArno — CHANGES_REQUESTED** [review]

File: apps/builder/src/features/analytics/components/StatsCards.tsx (hunk 1 above)
Comment (Jorgelig) [reply apps/builder/src/features/analytics/components/StatsCards.tsx]: done
